### ISSUE TITLE
Feature Request: add common snippet to task.yaml that is run before the prepare, execute, and restore sections

### ISSUE THREAD

**Issue by anonymouse64** [snapcore/spread#108]
Oftentimes we have code like this in our task.yamls:

```yaml
prepare: |
    #shellcheck source=tests/lib/nested.sh
    . "$TESTSLIB/nested.sh"
    prepare_something_from_nested.sh

restore: |
    #shellcheck source=tests/lib/nested.sh
    . "$TESTSLIB/nested.sh"
    restore_something_from_nested.sh

execute: |
    #shellcheck source=tests/lib/nested.sh
    . "$TESTSLIB/nested.sh"
    execute_something_from_nested.sh
```

it would be nice if we could somehow simplify this with just

```yaml
common: |
    #shellcheck source=tests/lib/nested.sh
    . "$TESTSLIB/nested.sh"

prepare: |
    prepare_something_from_nested.sh

restore: |
    restore_something_from_nested.sh

execute: |
    execute_something_from_nested.sh

```

this would reduce a lot of duplication we have in our spread task.yaml's in snapd.
